[project]
name = "langflowchallenges"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "graph-rag-example-helpers>=0.8.0",
    "langflow>=1.6.0",
    "pyvis>=0.3.2",
]
